const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Pin,
		C3.Plugins.Arr,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Dictionary,
		C3.Plugins.InstantGamesBridge,
		C3.Behaviors.wrap,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Exps.TouchID,
		C3.Plugins.Touch.Exps.XForID,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Touch.Exps.YForID,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Cnds.PickTopBottom,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.Pin.Exps.PinnedUID,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.RotateTowardAngle,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.System.Acts.SortZOrderByInstVar,
		C3.Plugins.Sprite.Exps.ObjectTypeName,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.layerindex,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialOpened,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedOpened,
		C3.Plugins.InstantGamesBridge.Acts.ShowInterstitial,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialFailed,
		C3.Plugins.InstantGamesBridge.Cnds.OnInterstitialClosed,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedFailed,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedClosed,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.InstantGamesBridge.Acts.ShowRewarded,
		C3.Plugins.InstantGamesBridge.Cnds.OnRewardedRewarded,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Exps.ObjectTypeName,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.InstantGamesBridge.Acts.SendMessage,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageHeight,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Exps.anglelerp,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{Fade: 0},
	{FlashSnapshot: 0},
	{ShaderSnapshot: 0},
	{Tween: 0},
	{FrameSnapshot: 0},
	{Pin: 0},
	{ImageSnapshot: 0},
	{Array1: 0},
	{Array2: 0},
	{Array3: 0},
	{Array4: 0},
	{Array0: 0},
	{TouchId: 0},
	{FurnitureButton: 0},
	{FurnCatButton: 0},
	{HideFrButton: 0},
	{CharactersButton: 0},
	{Sound_Button: 0},
	{FurnitureButton2: 0},
	{FurnitureButton3: 0},
	{TouchID: 0},
	{Bedroom: 0},
	{Bathroom: 0},
	{Kitchen: 0},
	{LivingRoom: 0},
	{Flowers: 0},
	{CatID: 0},
	{ColorIcon: 0},
	{ColorIconDop: 0},
	{FirstFloor: 0},
	{TwoFloor: 0},
	{ThreeFloor: 0},
	{Sprite: 0},
	{touchid: 0},
	{touchX: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Touch: 0},
	{Move_New_Layout: 0},
	{FadeOut: 0},
	{FadeIn: 0},
	{Sprite2: 0},
	{TiledBackground: 0},
	{Hide: 0},
	{Block: 0},
	{Sprite4: 0},
	{Sprite6: 0},
	{Sprite8: 0},
	{SortY: 0},
	{BlockSortZ: 0},
	{Variable_Array_Show: 0},
	{ArrayCurX: 0},
	{Xcanv: 0},
	{Ycanv: 0},
	{BlockZ: 0},
	{kes: 0},
	{HandLeft: 0},
	{HandRight: 0},
	{DragDrop: 0},
	{Characters: 0},
	{Sprite9: 0},
	{Particles: 0},
	{Sprite3: 0},
	{Sprite5: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{wall: 0},
	{LRwall: 0},
	{Polka: 0},
	{PinnedToysUID: 0},
	{Status: 0},
	{touchebl: 0},
	{startX: 0},
	{startY: 0},
	{dragging: 0},
	{SpecialItem: 0},
	{KeyForSave: 0},
	{KeySUIDSAVE: 0},
	{StartScale: 0},
	{Locked: 0},
	{Sprite7: 0},
	{list_head: 0},
	{Mouse: 0},
	{Sprite22: 0},
	{Audio: 0},
	{panel_bg_dark: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{SaveFurniture: 0},
	{SaveCharacters: 0},
	{Sprite11: 0},
	{TiledBackground4: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Dictionary: 0},
	{InstantGamesBridge: 0},
	{Sprite12: 0},
	{Sprite15: 0},
	{TiledBackground3: 0},
	{Wrap: 0},
	{Sine: 0},
	{Bullet: 0},
	{Sprite161: 0},
	{Sprite16: 0},
	{Sprite14: 0},
	{TiledBackground5: 0},
	{Sprite19: 0},
	{Id: 0},
	{ScrollInertia: 0},
	{Base: 0},
	{id: 0},
	{Sprite21: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{LRID: 0},
	{Sprite26: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{CatID2: 0},
	{StartX: 0},
	{StartY: 0},
	{ParentCatIcon: 0},
	{Icon_Category: 0},
	{ParentCatIconColor: 0},
	{TiledBackground8: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{Sprite27: 0},
	{ChColorBack: 0},
	{ChColorButton: 0},
	{Sprite13: 0},
	{Hair: 0},
	{Brown: 0},
	{Noise: 0},
	{Sprite20: 0},
	{Eyes: 0},
	{mouth: 0},
	{TShirt: 0},
	{Cap: 0},
	{Glasses: 0},
	{Sprite28: 0},
	{BackButton: 0},
	{Sprite29: 0},
	{Sprite30: 0},
	{Sprite31: 0},
	{Sprite32: 0},
	{DeleteVar: 0},
	{Sprite33: 0},
	{Particles3: 0},
	{Sprite34: 0},
	{Sprite35: 0},
	{CreateCharacterButton: 0},
	{CharactersCreator: 0},
	{Sprite10: 0},
	{ClothesSave: 0},
	{FurnitureSave: 0},
	{TiledBackground11: 0},
	{Sprite36: 0},
	{ButtonsFamily: 0},
	{Pin2: 0},
	{AllItemsOnMain: 0},
	{MiniCategory: 0},
	{ParentIcon: 0},
	{ColoringFamily: 0},
	{BobaFamily: 0},
	{SaveCharactersFamily: 0},
	{PinPolka: 0},
	{Family1: 0},
	{FirstPlay: 0},
	{TestOrNo: 0},
	{FirstFloorCameraX: 0},
	{TwoFloorCameraX: 0},
	{ThreeFloorCameraX: 0},
	{Stage: 0},
	{Move: 0},
	{First: 0},
	{FirstF: 0},
	{LoopCharIndex: 0},
	{Furniture_Category: 0},
	{Sound: 0},
	{CharactersCategory: 0},
	{CharactersUID: 0},
	{IDChar: 0},
	{CountShow: 0},
	{CurrentShow: 0},
	{CharUID: 0},
	{UID: 0},
	{DownOgranichitel: 0},
	{Acitve_drop: 0},
	{DragAndDrop_beh: 0},
	{Touch_start_Y: 0},
	{Touch_start_X: 0},
	{List_head_start_Y: 0},
	{Drag_drop_chuvstvitelnost: 0},
	{AnimationFrame: 0},
	{AnimationName: 0},
	{Height: 0},
	{PolkaStatus: 0},
	{Sprite7UID: 0},
	{CategoryItems: 0},
	{Sprite28LayerName: 0},
	{Sprite28id: 0},
	{Sprite28LayerName2: 0},
	{Sprite28Id2: 0},
	{Sprite7AnimUlock: 0},
	{Sprite7FrameUnlock: 0},
	{Sprite7AnimName: 0},
	{Sprite7AnimFrame: 0},
	{CharactersCount: 0},
	{Cur_TW: 0},
	{TriggerNext: 0},
	{BackgroundSpeed: 0},
	{CharCreateCategory: 0},
	{ColorCreateCategory: 0},
	{SpeedCatID: 0},
	{IDCharEdit: 0},
	{X: 0},
	{Y: 0},
	{Active: 0},
	{BackOffsetX: 0},
	{BackOffsetY: 0},
	{TouchStartXCourosel: 0},
	{PickBaseUID: 0},
	{ActiveDropCh: 0},
	{NewCharOrNot: 0},
	{PervousLayout: 0},
	{Poof: 0},
	{Scr: 0},
	{PickBaseUIDX: 0},
	{dd: 0},
	{dd2: 0},
	{Stop: 0},
	{ColorBase: 0},
	{CategoryColor: 0},
	{ColorValue: 0},
	{ObjTypeName: 0},
	{idnewitem: 0},
	{Check: 0},
	{LayoutCharName: 0},
	{BaseColor: 0},
	{BrownColor: 0},
	{NoiseColor: 0},
	{HairColor: 0},
	{XCharLayout: 0},
	{YCharLayout: 0}
];

self.InstanceType = {
	FlashSnapshot: class extends self.ITiledBackgroundInstance {},
	ShaderSnapshot: class extends self.ITiledBackgroundInstance {},
	FrameSnapshot: class extends self.ISpriteInstance {},
	ImageSnapshot: class extends self.ISpriteInstance {},
	Array1: class extends self.IArrayInstance {},
	Array2: class extends self.IArrayInstance {},
	Array3: class extends self.IArrayInstance {},
	Array4: class extends self.IArrayInstance {},
	Array0: class extends self.IArrayInstance {},
	FurnitureButton: class extends self.ISpriteInstance {},
	FurnCatButton: class extends self.ISpriteInstance {},
	HideFrButton: class extends self.ISpriteInstance {},
	CharactersButton: class extends self.ISpriteInstance {},
	Sound_Button: class extends self.ISpriteInstance {},
	FurnitureButton2: class extends self.ISpriteInstance {},
	FurnitureButton3: class extends self.ISpriteInstance {},
	Bedroom: class extends self.ISpriteInstance {},
	Bathroom: class extends self.ISpriteInstance {},
	Kitchen: class extends self.ISpriteInstance {},
	LivingRoom: class extends self.ISpriteInstance {},
	Flowers: class extends self.ISpriteInstance {},
	ColorIcon: class extends self.ISpriteInstance {},
	ColorIconDop: class extends self.ISpriteInstance {},
	FirstFloor: class extends self.IArrayInstance {},
	TwoFloor: class extends self.IArrayInstance {},
	ThreeFloor: class extends self.IArrayInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Move_New_Layout: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Characters: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	wall: class extends self.ITiledBackgroundInstance {},
	LRwall: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	list_head: class extends self.ITiledBackgroundInstance {},
	Mouse: class extends self.IInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	panel_bg_dark: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SaveFurniture: class extends self.IArrayInstance {},
	SaveCharacters: class extends self.IArrayInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	InstantGamesBridge: class extends self.IInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite161: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Base: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	ParentCatIcon: class extends self.ISpriteInstance {},
	Icon_Category: class extends self.ISpriteInstance {},
	ParentCatIconColor: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	ChColorBack: class extends self.ISpriteInstance {},
	ChColorButton: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Hair: class extends self.ISpriteInstance {},
	Brown: class extends self.ISpriteInstance {},
	Noise: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	Eyes: class extends self.ISpriteInstance {},
	mouth: class extends self.ISpriteInstance {},
	TShirt: class extends self.ISpriteInstance {},
	Cap: class extends self.ISpriteInstance {},
	Glasses: class extends self.ISpriteInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	BackButton: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	CreateCharacterButton: class extends self.ISpriteInstance {},
	CharactersCreator: class extends self.IArrayInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	ClothesSave: class extends self.IDictionaryInstance {},
	FurnitureSave: class extends self.IDictionaryInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	ButtonsFamily: class extends self.ISpriteInstance {},
	AllItemsOnMain: class extends self.ISpriteInstance {},
	MiniCategory: class extends self.ISpriteInstance {},
	ParentIcon: class extends self.ISpriteInstance {},
	ColoringFamily: class extends self.ISpriteInstance {},
	BobaFamily: class extends self.ISpriteInstance {},
	SaveCharactersFamily: class extends self.IArrayInstance {},
	Family1: class extends self.ISpriteInstance {}
}